name: Trigger auto deployment for node-hello-web

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/node-hello-web-AutoDeployTrigger-f5301adc-8f12-4f70-8fea-4b032256d739.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.NODEHELLOWEB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NODEHELLOWEB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NODEHELLOWEB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: pmtm001.azurecr.io
          registryUsername: ${{ secrets.NODEHELLOWEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NODEHELLOWEB_REGISTRY_PASSWORD }}
          containerAppName: node-hello-web
          resourceGroup: rg_helloweb
          imageToBuild: pmtm001.azurecr.io/node-hello-web:${{ github.sha }}
          


